# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'faraday', '~> 2.12'
gem 'rspec', '~> 3.13'
gem 'rspec-mock', '~> 0.4.0'

gem 'rubocop', '~> 1.71'

gem "byebug", "~> 11.1"

gem "debug", "~> 1.10"
