# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in sample_prj_2025_02_10.gemspec
gemspec

gem 'rake', '~> 13.0'

gem 'standard', '~> 1.3'

gem 'minitest', '~> 5.25', group: :development
gem 'rubocop', '~> 1.71', group: :development
gem 'test', '~> 1.0', group: :development

gem 'faraday', '~> 2.12'
