services:
  # 前提: ビルド環境でpnpm installしている

  dev:
    build:
      context: .
      target: dev # Dockerfileのどのイメージを使うか指定
    working_dir: /app # コマンドを実行するディレクトリ
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store # pnpmでインストールしたファイルを配置
      - node_modules:/app/node_modules
    command: pnpm dev

  test:
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - node_modules:/app/node_modules
    command: pnpm test

  prod:
    build:
      context: .
      target: runner
    working_dir: /app
    command: node dist/index.js

volumes:
  pnpm-store:
  node_modules:
