# 開発用にrails sidekiq, redisのコンテナを起動する
# `docker compose up --build`で実行すること
services:
  app:
    build:
      context: .
      target: rails_app
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
  sidekiq:
    build:
      context: .
      target: sidekiq_app
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  redis:
    build:
      context: .
      target: sidekiq_redis
      dockerfile: Dockerfile
    volumes:
      - redis-data:/data
volumes:
  redis-data: {}
