# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in daily_dir_maker.gemspec
gemspec

gem 'irb'
gem 'rake', '~> 13.0'

gem 'standard', '~> 1.3'

group :development, :test do
  gem 'rubocop', '~> 1.71', groups: %i[development test]
end

gem "minitest", "~> 5.25", :group => :test

gem "byebug", "~> 11.1", :group => :test
