services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
  prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod